name: "PMD Annotate Source Code"
description: "Creates code annotations from a PMD report"
author: "Rodolphe Blancho"

inputs:
  reportfile:
    description: |
      Location of the report file relative to the project root.
      This action supports only reports using the JSON format.
    required: true
    default: 'pmd-report.json'
  dir:
    description: |
      Required if the report was created using the `-shortnames` option and
      the `-dir` option was set to a different value.
      This value should be the same as the value given to `-dir` during
      the report creation.
    required: false
  min-error-priority:
    description: |
      From 1 (highest) to 5 (lowest). Violations with a higher priority than
      this value will be reported as errors, the other ones will be reported
      as warnings. Default to 5 (every violation is considered as an error)
    required: false
    default: '5'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -reportfile
    - ${{ inputs.reportfile }}
    - ${{ inputs.dir && '-dir' }}
    - ${{ inputs.dir }}
    - -min-error-priority
    - ${{ inputs.min-error-priority }}

branding:
  icon: 'flag'
  color: 'red'
